version: '3.9'

services:
  mongodb:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "27017:27017"
    env_file:
      - ../.env
   # volumes:
      #- ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro