version: '3.9'

services:
  mongodb:
    image: mongo:6.0.1
    ports:
      - 27017:27017
    env_file:
      - ../.env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro